### ISSUE TITLE
Business Value: Persona Missing

### ISSUE THREAD

**Issue by kaustubhkulkarni1509** [SJSUFall2019-CMPE272/Smart-MOM#2]
The most important thing for any enterprise level project is target audience. For the given project, target audience is missing which leads me to conclude, anyone can use this product. It can be used to track important points of casual discussion between a group of people talking on some generic topic and it can also be used in board meetings of companies.
To define a persona three things are required. Firstly, who the customers are, what they need and how product provides a solution. The project is clear on what and how but who is missing here. As our professor said, “if the product is for everyone then it is for no one”. Personas that are broad enough to cover a big product end up being too vaguely described which is what I believe happened here.

**Comment by shriyavanvari** [comment]
Persona defined in readme file.
